env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent: [ error, 4, { "SwitchCase": 1 } ]
  linebreak-style: [ error, unix ]
  no-console: off
  quotes: [ error, single ]
  semi: [ error, always ]
